import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Arimo } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({ subsets: ["latin"], variable: '--font-quicksand' })
const arimo = Arimo({ subsets: ["latin"], variable: '--font-arimo'})

export const metadata: Metadata = {
  title: "Albums for Miles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arimo.variable}>{children}</body>
    </html>
  );
}
