import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const agrandir = localFont({ src: '../../public/fonts/Agrandir-Regular.otf', variable: '--font-agrandir'});




export const metadata: Metadata = {
  title: "Albums for Miles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${agrandir.variable}` }>{children}</body>
    </html>
  );
}
